function [g,Dg] = algebraicRhs(in1,in2,u1)
%ALGEBRAICRHS
%    [G,DG] = ALGEBRAICRHS(IN1,IN2,U1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    01-Oct-2020 10:54:51

x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
z1 = in2(1,:);
z2 = in2(2,:);
t2 = x1.^2;
t3 = x2.^2;
t5 = z2.*5.0;
t4 = t3.^2;
g = [-t5+x3+z1;t2+t3.*6.0e+1+t5-x3-z1+t2.*z2.*2.0e+1+t4.*z2.*1.8e+2+t3.*z1.^2.*6.0-x2.^3.*2.0];
if nargout > 1
    Dg = reshape([1.0,t3.*z1.*1.2e+1-1.0,-5.0,t2.*2.0e+1+t4.*1.8e+2+5.0],[2,2]);
end
