function f = differentialRhs(in1,in2,u1)
%DIFFERENTIALRHS
%    F = DIFFERENTIALRHS(IN1,IN2,U1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    01-Oct-2020 10:54:51

x1 = in1(1,:);
x2 = in1(2,:);
z1 = in2(1,:);
z2 = in2(2,:);
f = [x1.*z2.*1.0e+1;x2.^2.*z2.*-3.0e+1-z1.^2-1.0e+1;z1-z2.*5.0];
